# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  android: circleci/android@0.2.3

jobs:
  build:
    executor: android/android
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - run:
          name: Adding TMDB API to build environment
          command: echo "tmdb.api.key=\"$TMDB_API_KEY\"" >> local.properties
      - run:
          name: Adding DB Encryption Key to build environment
          command: echo "db.passphrase=\"$DB_PASSPHRASE\"" >> local.properties
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: "android-orb-v1-{{ epoch }}"
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build --stacktrace
      - store_artifacts:
          path: app/build/reports
          destination: app/reports
      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: favorite/build/reports
          destination: favorite/reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: favorite/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
